# -------------------------------------------------------------------------------------------------------------------- #
# Configuration tutorial                                                                                               #
# -------------------------------------------------------------------------------------------------------------------- #
# Name :                                                                                                               #
#     The enchantment name, This name is used to be showed in item description                                         #
# Description :                                                                                                        #
#     This description will be only showed on GUI                                                                      #
# Applicable :                                                                                                         #
#     Items that this enchantment can be applied to, You can use Items list defined in main config file or materials   #
# Treasure :                                                                                                           #
#     Treasure enchantments can not be obtained with enchantment table, These enchantments have a cyan color           #
# Cursed :                                                                                                             #
#     Cursed enchantments have a red color and means they has negative effects. A cursed enchantment can be obtained   #
#     with enchantment table while enchanting unless you specify it as treasure (Red color overrides the cyan)         #
# Multiplier :                                                                                                         #
#     While using anvil/enchantment table these values determine the enchantment price and value, Higher values means  #
#     more cost while enchanting                                                                                       #
# MaxLevel :                                                                                                           #
#     This number determine how many levels this enchantment has.                                                      #
#     Unlike the vanilla enchantments, Custom enchantments can not pass the max level or be lower than level 1         #
# Lore :                                                                                                               #
#     This section determines level details, This section is different in each enchantment                             #
#     This section can be one string or a list of strings, List index will determine the lore for level                #
#     If the index was not found it will use the first one, This section can also use levels placeholders              #
# Levels :                                                                                                             #
#     This section is the enchantment functionality configuration section and must be started with '1' and defined for #
#     each level below max level. For some enchantments which has no configuration this section will be ignored        #
# -------------------------------------------------------------------------------------------------------------------- #

Name: Example
Description: |-
  §8Description of enchant

  §eApplicable on §fItems
  §cConflicts list
  §c- §fEnchants
Lore:
  - Item lore
Applicable: []
Conflicts: []
Treasure: false
Cursed: false
Multiplier: 1
MaxLevel: 5
VillagersTrading: true
PiglinBartering: false
Fishing: true
Loot:
  - OVER_WORLD
  - NETHER
  - END
Levels:
  1:
    Chance: 5
  2:
    Chance: 10
  3:
    Chance: 25
  4:
    Chance: 50
  5:
    Chance: 85